import Head from "next/head";
import { Poppins } from "@next/font/google";
import { MdNavigateNext } from "react-icons/md";
import { BsThreeDotsVertical } from "react-icons/bs";
import { IoClose } from "react-icons/io5";
import { useState } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export default function Home() {
  const [toogle, setToogle] = useState(false);

  const handleToogle = () => {
    setToogle(!toogle);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${poppins.className}`}>
        <nav className="relative mx-auto flex w-11/12 max-w-[1280px] items-center justify-between py-4">
          <div className="flex flex-row items-center space-x-8">
            <span className="text-lg font-bold uppercase">Localhost</span>
            <div className="hidden lg:flex">
              <ul className="flex space-x-8">
                <li>Products</li>
                <li>Integrations</li>
                <li>Recipes</li>
                <li>Resource</li>
              </ul>
            </div>
          </div>

          <div className="flex flex-row items-center">
            <button className="lg:hidden" onClick={handleToogle}>
              <span className="sr-only">Toggle menu</span>
              <BsThreeDotsVertical className="h-6 w-6" />
            </button>
            <ul
              className={`absolute flex flex-col items-end justify-end gap-x-9 space-y-4 rounded-lg bg-white p-4 shadow-lg transition-all duration-300 md:w-4/12 lg:static lg:mt-0 lg:w-auto lg:flex-row lg:items-center lg:space-y-0 lg:rounded-none lg:bg-transparent lg:p-0 lg:shadow-none ${
                toogle ? "right-0 top-2" : "-right-full top-2"
              }`}
            >
              <button className="lg:hidden" onClick={handleToogle}>
                <span className="sr-only">Toggle Close</span>
                <IoClose className="h-6 w-6" />
              </button>
              <li>Login</li>
              <button className="flex items-center rounded-md bg-blue-600 px-4 py-2 text-white">
                Try it free
                <span>
                  <MdNavigateNext className="h-6 w-6" />
                </span>
              </button>
            </ul>
          </div>
        </nav>
      </main>
    </>
  );
}
